### ISSUE TITLE
validateHash(): use hash_equals() instead of ===

### ISSUE THREAD

**Issue by paragonie-scott** [IcyApril/CryptoLib#10]
https://github.com/IcyApril/CryptoLib/blob/master/src/CryptoLib.php#L233

http://blog.ircmaxell.com/2014/11/its-all-about-time.html

**Comment by IcyApril** [comment]
So sorry for the slow reply! Accordingly updated: https://github.com/IcyApril/CryptoLib/blob/master/src/CryptoLib.php#L283
