### ISSUE TITLE
Change class version in CryptoLib.php

### ISSUE THREAD

**Issue by nikolaybaychenko** [IcyApril/CryptoLib#14]
Change class version from `v0.8 Christmas` to `v1.0 Conqueror` in class description in CryptoLib.php

From CryptoLib.php:
```
<?php
namespace IcyApril;
    /**
     * Class CryptoLib (v0.8 Christmas)
     * Created by Junade Ali
     * Requires OpenSSL, MCrypt > 2.4.x, PHP 5.3.0+
     */

...
```

**Comment by WhiteLoti** [comment]
CryptoLib should be deprecated from projects. Libsodium is natively supported in PHP 7.2+ and has support for almost every function CryptoLib has, and it also doesn’t use Mcrypt.
