### ISSUE TITLE
PHP 5.4 Fatal error with use of function hash_pbkdf2()

### ISSUE THREAD

**Issue by pavanyelavarthi** [IcyApril/CryptoLib#4]
Fatal error: Call to undefined function hash_pbkdf2() in CryptoLib.php on line 193.
This is real bummer, as u mentioned in your documentation and in file that it will work with "Requires OpenSSL, MCrypt > 2.4.x, PHP 5.3.0+".

hash_pbkdf2 is available in PHP code from 5.5 version only.

**Comment by IcyApril** [comment]
Apologies for this. I have updated the documentation to refer to the correct version.

**Comment by anoopkp06** [comment]
Here is the solution  

/**
	* Method to create hash_pbkdf2  (for php v<5.5)
	* @param null
	* @access public
	* @return null
	*/
	
	function hash_pbkdf2($algo, $password, $salt, $count, $length = 0, $raw_output = false)
    {
        if (!in_array(strtolower($algo), hash_algos())) trigger_error(__FUNCTION__ . '(): Unknown hashing algorithm: ' . $algo, E_USER_WARNING);
        if (!is_numeric($count)) trigger_error(__FUNCTION__ . '(): expects parameter 4 to be long, ' . gettype($count) . ' given', E_USER_WARNING);
        if (!is_numeric($length)) trigger_error(__FUNCTION__ . '(): expects parameter 5 to be long, ' . gettype($length) . ' given', E_USER_WARNING);
        if ($count <= 0) trigger_error(__FUNCTION__ . '(): Iterations must be a positive integer: ' . $count, E_USER_WARNING);
        if ($length < 0) trigger_error(__FUNCTION__ . '(): Length must be greater than or equal to 0: ' . $length, E_USER_WARNING);

        $output = '';
        $block_count = $length ? ceil($length / strlen(hash($algo, '', $raw_output))) : 1;
        for ($i = 1; $i <= $block_count; $i++)
        {
            $last = $xorsum = hash_hmac($algo, $salt . pack('N', $i), $password, true);
            for ($j = 1; $j < $count; $j++)
            {
                $xorsum ^= ($last = hash_hmac($algo, $last, $password, true));
            }
            $output .= $xorsum;
        }

        if (!$raw_output) $output = bin2hex($output);
        return $length ? substr($output, 0, $length) : $output;
    }

**Comment by anoopkp06** [comment]
function call will be 
if (!function_exists('hash_pbkdf2'))
		{			 
			$new_hash = $this->hash_pbkdf2("sha256", $repository_shared_secret, $transaction_salt, 5000, 64, true);		 
			$secretDerivedKey = base64_encode($new_hash);
		}
		else
		{
			$secretDerivedKey = base64_encode(hash_pbkdf2("sha256", $repository_shared_secret, $transaction_salt, 5000, 64, true));	 			 
		}
