### ISSUE TITLE
Make this available via composer

### ISSUE THREAD

**Issue by tzfrs** [IcyApril/CryptoLib#6]
Hi,

is it possible that this library will be made available for composer? Sucks that I have every library via composer except this awesome one here.

**Comment by lchachurski** [comment]
I've noticed it's available but current version is not stable according to compser:

"Could not find package icyapril/cryptolib at any version for your minimum-stability (stable)"

**Comment by IcyApril** [comment]
So sorry for the slow reply (literally took years). There is now a v1.0.0. https://packagist.org/packages/icyapril/cryptolib
